Trip Reservation System/Trip Reservation System/Models/Passenger.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Trip_Reservation_System.Models
{
    public class Passenger
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "you have to enter your name")]
        [StringLength(20)]
        [Display(Name = "New password")]
        public string Name { get; set; }


        [Required(ErrorMessage = "you have to enter your Username")]
        [StringLength(20)]
        public string UserName { get; set; }



        [Required(ErrorMessage = "you have to enter your Password")]
        [DataType(DataType.Password)]
        [MinLength(5)]
        [StringLength(10)]
        public string Password { get; set; }



        [Compare("Password", ErrorMessage = "you have to enter your confirm Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "you have to enter your Adress")]
        [StringLength(10)]

        public string Adress { get; set; }
        [Required(ErrorMessage = "you have to enter your Date of Birth")]

        public DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "you have to enter your Email")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3]\.)|(([\w-]+\.)+))([a-zA-Z{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter valid email.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "you have to enter your SSN")]

        public long SSN { get; set; }
        [Required(ErrorMessage = "you have to enter your Gender")]


        public string Gender { get; set; }
        public float Wallet { get; set; }
        public bool Block { get; set; }
        public bool IsAdmin { get; set; }
    }
}

Trip Reservation System/Trip Reservation System/Controllers/PassengerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;//email
using System.Web.Mvc;
using Trip_Reservation_System.Models;

namespace Trip_Reservation_System.Controllers
{
    public class PassengerController : Controller
    {
        public int sessid;
        ApplicationDbContext DB = new ApplicationDbContext();
        // GET: Passenger


        /* public ActionResult Index()
         {



             return View(DB.Passengers.ToList());
         }*/
        public ActionResult resetPassword()
        {

            return View();
        }

        /*  public ActionResult resetPassword()
          {
              Random rand = new Random((int)DateTime.Now.Ticks);
              int RandomNumber;
              RandomNumber = rand.Next(100000, 999999);
              SendMail()
              return View();
          }*/

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Passenger psg)
        {
            var SeachData = DB.Passengers.Where(x => x.UserName.Equals(psg.UserName)).SingleOrDefault();
            if (SeachData == null)
            {
                if (ModelState.IsValid)
                {
                    DB.Passengers.Add(psg);
                    DB.SaveChanges();
                    string x = psg.Name;
                    SendMail(psg, x);
                    ModelState.Clear();
                    ViewBag.text = psg.Name + " registered sucessfully";
                }
            }
            else { ViewBag.usernamevalid = "usrname is taken"; }

            return View();

        }


        public void SendMail(Passenger psg, string x)
        {
            WebMail.SmtpServer = "smtp.gmail.com";
            //gmail port to send emails  
            WebMail.SmtpPort = 587;
            WebMail.SmtpUseDefaultCredentials = true;
            //sending emails with secure protocol  
            WebMail.EnableSsl = true;
            //EmailId used to send emails from application  
            WebMail.UserName = "khaaledessaam@gmail.com";
            WebMail.Password = "khaled18";

            //Sender email address.  
            WebMail.From = "khaaledessaam@gmail.com";

            //Send email  

            WebMail.Send(psg.Email, "hello" + x, "hello man how are you");




        }













        public ActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Login(Passenger psg)
        {
            /* if (psg.UserName.Equals("admin") && psg.Password.Equals("admin"))
             {
                 Session["AdminID"] = "Admin";
                 return RedirectToAction("AdminPanel");
             }
             else
             {*/
            var user = DB.Passengers.Where(u => u.UserName == psg.UserName && u.Password == psg.Password).FirstOrDefault();
            if (user.Block == true)
            {
                ViewBag.text = psg.Name + " your account is disabled";
            }
            else
            {
                if (user.IsAdmin == true && user != null && user.Block == false)
                {
                    Session["AdminID"] = "Admin";
                    return RedirectToAction("AdminPanel");
                }
                else
                {
                    if (user != null)
                    {
                        Session["PassengerID"] = user.Id.ToString();
                        Session["UserName"] = psg.UserName.ToString();
                        //  sessid = user.Id;
                        return RedirectToAction("LoggedIn");
                    }
                    else { ModelState.AddModelError("", "username or password is wrong"); }
                }
            }
            return View();
        }
        //[Authorize]
        public ActionResult LoggedIn()
        {
            if (Session["PassengerID"] != null)
            {
                return View();
            }
            else { return RedirectToAction("Login"); }

        }
        public ActionResult AdminPanel()
        {
            if (Session["AdminID"] != null)
            {
                return View();
            }
            else { return RedirectToAction("Login"); }

        }


        public JsonResult CheckUsernameAvailability(string userdata)
        {
            System.Threading.Thread.Sleep(200);
            var SeachData = DB.Passengers.Where(x => x.UserName.Equals(userdata)).SingleOrDefault();
            if (SeachData != null)
            {

                return Json(1);
            }
            else
            {

                return Json(0);
            }

        }
        public JsonResult CheckUserEmailAvailability(string userdata1)
        {
            System.Threading.Thread.Sleep(200);
            var SeachData = DB.Passengers.Where(x => x.Email.Equals(userdata1)).SingleOrDefault();
            if (SeachData != null)
            {

                return Json(1);
            }
            else
            {

                return Json(0);
            }

        }

        public ActionResult addLine()
        {
            if (Session["AdminID"] != null)
            {
                return View();
            }
            else { return RedirectToAction("Login"); }
        }

        public ActionResult Logout()
        {
            Session.Clear();

            return RedirectToAction("Login");
        }
        [HttpGet]
        public ActionResult CancelReservation(int id)

        {
            // int var2 =sessid;
            //   int y = 1;
            //  Session["PassengerID"]=y;
            // int y = Convert.ToInt32(Session["PassengerID"].ToString());
            //  Console.WriteLine(y);
            if (Session["PassengerID"] != null)
            {
                var usertickets = DB.Ticket.ToList().Where(x => x.PassengerId == id/* Convert.ToInt32(Session["PassengerID"])*/);
                return View(usertickets);
            }
            else { return RedirectToAction("Login"); }
            //int id = 1;
            //Convert.ToInt32(Session["PassengerID"])
        }

        public ActionResult Cancel(int NumberOfseats, DateTime date, int BusID, int UserId, float TotalPrice)
        {
            var trip = DB.Trips.SingleOrDefault(X => X.BusId == BusID && X.FullDate == date);
            trip.AvailsbleSeats = trip.AvailsbleSeats + NumberOfseats;
            trip.ReservedSeats = trip.ReservedSeats - NumberOfseats;
            DB.SaveChanges();

            var UserWallet = DB.Passengers.SingleOrDefault(X => X.Id == UserId);
            UserWallet.Wallet = UserWallet.Wallet + TotalPrice;
            DB.SaveChanges();
            return RedirectToAction("CancelReservation");
        }
    }
}

Trip Reservation System/Trip Reservation System/Views/Passenger/AdminPanel.cshtml
@{
    ViewBag.Title = "AdminPanel";
}

<h2>AdminPanel</h2>
@if (Session["AdminId"] != null)
{
    <h4>hello @Session["AdminId"].ToString()</h4>
    @Html.ActionLink("add line", "addLine", "Passenger")
    @Html.ActionLink("Logout", "Logout", "Passenger")
}

Trip Reservation System/Trip Reservation System/Views/Passenger/CancelReservation.cshtml
@model IEnumerable<Trip_Reservation_System.Models.Ticket>

@{
    ViewBag.Title = "CancelReservation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cancel Reservation</h2>


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.ReservationDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocFrom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeFrom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfseats)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.ReservationDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfseats)
            </td>
            <td>
                <!-- --> @Html.ActionLink("Cancel", "Cancel", new
                    {
                        NumberOfseats = item.NumberOfseats,
                        date = item.ReservationDay,
                        BusID = item.BusId,
                        UserId = item.PassengerId,
                        TotalPrice = item.TotalPrice
                    })
            </td>
        </tr>
    }

</table>

Trip Reservation System/Trip Reservation System/Views/Passenger/LoggedIn.cshtml
@{
    ViewBag.Title = "LoggedIn";
}

@if (Session["PassengerId"] != null)
{
    <h4>hello @Session["UserName"].ToString()</h4>
    @Html.ActionLink("Book Ticket", "Logout", "Passenger")
    @Html.ActionLink("Cancel Ticket", "CancelReservation", new { id = Convert.ToInt32(Session["PassengerID"]) })
    @Html.ActionLink("Logout", "Logout", "Passenger")
}

Trip Reservation System/Trip Reservation System/Views/Passenger/Login.cshtml
@model Trip_Reservation_System.Models.Passenger

@{
    ViewBag.Title = "Login";
}
 
<h2>Login</h2>
@if (ViewBag.text != null)
{<div class="alert alert-danger" role="alert">
        <b>@ViewBag.text</b>
    </div>


}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Passenger</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trip Reservation System/Trip Reservation System/Views/Passenger/Register.cshtml
@model Trip_Reservation_System.Models.Passenger

@{
    ViewBag.Title = "Register";
    @Scripts.Render("~/bundles/jquery")
}
<link rel="text/css" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
<h2>Register</h2>
<link href="~/Content/jquery-ui.min.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Passenger</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (ViewBag.text != null)
        {
            <div class="alert alert-success" role="alert">
                <b>@ViewBag.text</b>
            </div>

        }
        @if (ViewBag.usernamevalid != null)
        {
            <div class="alert alert-danger" role="alert">
                <b>@ViewBag.usernamevalid</b>
            </div>

        }
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", type = "text", id = "Username", name = "Username", placeholder = "Enter Username", onchange = "UserCheck()" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
            <div class="row">
                <label class="col-sm-2"></label>
                <div class="col-sm-10">
                    <p id="Status" />
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DateOfBirth, htmlAttributes: new { @class = "form-control", id = "datepicker" })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">


                @Html.RadioButtonFor(m => m.Gender, "Male", new { htmlAttributes = new { @class = "form-control " } }) male &nbsp;&nbsp;&nbsp;&nbsp;
                @Html.RadioButtonFor(m => m.Gender, "FeMale", new { htmlAttributes = new { @class = "form-control " } }) female
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>



        @*@Html.TextBoxFor(model => model.SSN, htmlAttributes: new { id = "date" , type ="date" })*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
}

<script>
    function UserCheck() {
        $("#Status").html("Checking...");
        $.post("@Url.Action("CheckUsernameAvailability", "Passenger")",
            {
                userdata: $("#Username").val()
            },
        function (data) {
            if (data == 0) {
                $("#Status").html('<font color="Green">Available !. you can take it.</font>');
                $("#Username").css("border-color", "Green");

            }
            else {
                $("#Status").html('<font color="Red">That name is taken.Try Another.</font>');
                $("#Username").css("border-color", "Red");
            }
        });
    }</script>



<script type="text/javascript">
  $( function() {
      $("#datepicker").datepicker({
          dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, yearRange: "2010:2015"
      , minDate: new Date(2010, 0, 1), maxDate: new Date(2018, 0, 1)
      });
  } );
</script>